module ru.nikidzawa.golink {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
    requires javafx.media;
    requires javafx.base;
    requires javafx.graphics;
    requires javafx.swing;
    requires GNAvatarView;
    requires spring.beans;
    requires spring.core;
    requires spring.data.jpa;
    requires spring.aop;
    requires org.postgresql.jdbc;
    requires spring.data.commons;
    requires spring.tx;
    requires spring.expression;
    requires spring.context;
    requires java.sql;
    requires spring.boot.starter;
    requires spring.boot;
    requires spring.boot.autoconfigure;
    requires jakarta.persistence;
    requires jakarta.annotation;
    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires net.synedra.validatorfx;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires org.hibernate.orm.core;
    requires lombok;
    requires twilio;
    requires org.slf4j;
    requires spring.boot.starter.logging;
    requires jul.to.slf4j;
    requires spring.orm;
    requires javafx.graphicsEmpty;
    requires javafx.mediaEmpty;
    requires GoLinkNetworkAPI;
    requires javafx.controlsEmpty;

    opens ru.nikidzawa.golink to javafx.fxml, spring.core, org.hibernate.orm.core;
    exports ru.nikidzawa.golink;
    exports ru.nikidzawa.golink.FXControllers.helpers;
    opens ru.nikidzawa.golink.services.GUI.TrayIcon to javafx.fxml;
    exports ru.nikidzawa.golink.FXControllers;
    opens ru.nikidzawa.golink.FXControllers to javafx.fxml, org.hibernate.orm.core, spring.core;
    opens img;
    opens ru.nikidzawa.golink.FXControllers.helpers to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.FXControllers.Configurations;
    opens ru.nikidzawa.golink.FXControllers.Configurations to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.FXControllers.cash;
    opens ru.nikidzawa.golink.FXControllers.cash to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.services.sound;
    opens ru.nikidzawa.golink.services.sound to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.services.SMSAuthenticate;
    opens ru.nikidzawa.golink.services.SMSAuthenticate to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.services.GUI.GrapgicPatterns;
    opens ru.nikidzawa.golink.services.GUI.GrapgicPatterns to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.services.GUI;
    opens ru.nikidzawa.golink.services.GUI to javafx.fxml, org.hibernate.orm.core, spring.core;
}