module ru.nikidzawa.golink {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
    requires javafx.media;
    requires javafx.base;
    requires javafx.graphics;
    requires javafx.swing;
    requires com.gluonhq.charm.glisten;
    requires GNAvatarView;
    requires spring.beans;
    requires spring.core;
    requires spring.data.jpa;
    requires spring.aop;
    requires org.postgresql.jdbc;
    requires spring.data.commons;
    requires spring.tx;
    requires spring.expression;
    requires spring.context;
    requires java.sql;
    requires spring.boot.starter;
    requires spring.boot;
    requires spring.boot.autoconfigure;
    requires jakarta.persistence;
    requires jakarta.annotation;
    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires net.synedra.validatorfx;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires eu.hansolo.tilesfx;
    requires org.hibernate.orm.core;
    requires lombok;
    requires twilio;
    requires org.slf4j;
    requires spring.boot.starter.logging;
    requires jul.to.slf4j;
    requires JavaFXEmojiTextFlow.emojitwo;
    requires libphonenumber;

    opens ru.nikidzawa.golink to javafx.fxml, spring.core, org.hibernate.orm.core;
    exports ru.nikidzawa.golink;
    exports ru.nikidzawa.golink.services.SystemOfControlServers;
    opens ru.nikidzawa.golink.services.SystemOfControlServers to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.store.entities;
    opens ru.nikidzawa.golink.store.entities to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.store.enums;
    opens ru.nikidzawa.golink.store.enums to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.store.repositories;
    opens ru.nikidzawa.golink.store.repositories to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.network;
    opens ru.nikidzawa.golink.network to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.services.GoMessage;
    opens ru.nikidzawa.golink.services.GoMessage to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.services;
    opens ru.nikidzawa.golink.services to javafx.fxml, org.hibernate.orm.core, spring.core;
    exports ru.nikidzawa.golink.FXControllers;
    opens ru.nikidzawa.golink.FXControllers to javafx.fxml, org.hibernate.orm.core, spring.core;
    opens img;
}